<?xml version="1.0" encoding="UTF-8"?>
<!--Nombre: David Ruiz
Curso: Daw1
Fecha: 04/04/2025
Ejercicio 6
-->
<!--Ejercicio paises-->
<!DOCTYPE paises [
    <!ELEMENT paises (pais*)>
    <!ELEMENT pais (nombre, unionEuropa?, otan?)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT unionEuropa EMPTY>
    <!ELEMENT otan EMPTY>
]>
<paises>
    <pais>
        <nombre>Espa√±a</nombre>
        <unionEuropa/>
        <otan/>
    </pais>
    <pais>
        <nombre>Noruega</nombre>
        <otan/>
    </pais>
    <pais>
        <nombre>Austria</nombre>
        <unionEuropa/>
    </pais>
</paises>
