<?xml version="1.0" encoding="UTF-8"?>
<!--Nombre: David Ruiz
Curso: Daw1
Fecha: 04/04/2025
Ejercicio 7
-->
<!--Ejercicio codigos de colores-->
<!DOCTYPE colores [
    <!ELEMENT colores (color*)>
    <!ELEMENT color (nombreSvg, rgb?, cmyk?)>
    <!ELEMENT nombreSvg (#PCDATA)>
    <!ELEMENT rgb (#PCDATA)>
    <!ELEMENT cmyk (#PCDATA)>
]>
<colores>
    <color>
        <nombreSvg>Purple</nombreSvg>
        <rgb>#800080</rgb>
    </color>
    <color>
        <nombreSvg>Purple</nombreSvg>
        <cmyk>#40F0FF</cmyk>
    </color>
</colores>
