<?xml version="1.0" encoding="UTF-8"?>
<!--Nombre: David Ruiz
Curso: Daw1
Fecha: 04/04/2025
Ejercicio 9
-->
<!--Ejercicio mensajes-->
<!DOCTYPE mensajes [
  <!ELEMENT mensajes (mensaje+)>
  <!ELEMENT mensaje (de, para, hora, texto)>
  <!ELEMENT de (#PCDATA)>
  <!ELEMENT para (#PCDATA)>
  <!ELEMENT hora (#PCDATA)>
  <!ELEMENT texto (#PCDATA|strong)*>
  <!ELEMENT strong (#PCDATA)>
]>
<mensajes>
  <mensaje>
    <de>Pepe (pepe@example.com)</de>
    <para>Juan (juan@example.com)</para>
    <hora>28/02/2011 17:48:23.61</hora>
    <texto>Hola, Juan, ¿qué haces?</texto>
  </mensaje>
  <mensaje>
    <de>Juan (juan@example.com)</de>
    <para>Pepe (pepe@example.com)</para>
    <hora>28/02/2011 17:54:09.28</hora>
    <texto>Aquí, aprendiendo <strong>XML</strong></texto>
  </mensaje>
</mensajes>
